version: '3.7'
services:
  api:
    restart: always
    build: ./api
    command: npm run dev
    volumes:
      - ./api:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  webapp:
    restart: always
    build: ./webapp
    command: npm run dev
    volumes:
      - ./webapp:/usr/app/
      - /usr/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - api 

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: urlDb
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: